server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html tablero-rca.html;

    auth_basic "Tablero RCA SECON - Acceso Restringido";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        try_files $uri $uri/ =404;
    }
}
